# Generated by Django 4.2.15 on 2025-09-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nexapp_radius", "0040_rename_phonetoken_index"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="phonetoken",
            new_name="nexapp_radi_user_id_057d0f_idx",
            old_name="openwisp_ra_user_id_9fe207_idx",
        ),
        migrations.RenameIndex(
            model_name="phonetoken",
            new_name="nexapp_radi_user_id_30aa8d_idx",
            old_name="openwisp_ra_user_id_d4dd52_idx",
        ),
    ]
