# Generated by Django 4.2.15 on 2025-09-06 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "nexapp_radius",
            "0041_rename_openwisp_ra_user_id_9fe207_idx_nexapp_radi_user_id_057d0f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereduser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="registered_user",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
